#!/bin/bash

echo -n "How much money did u get after the sale?"
read sale
echo -n "How much cash did u keep after the sale?"
read cash

payment=$(($sale - $cash)) 

if [ $payment -lt 0 ]; then 
	echo "NO CASH!"
elif [ $payment -gt 100 ]; then 
	echo "BIG MONEY"
else
	echo "TF ARE U SAYING"
fi
